version: '3.8'

services:
  app_nginx:
    image: nginx:latest
    container_name: app_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    depends_on:
      - app_php-fpm

  app_php-fpm:
    image: php:8.0-fpm
    container_name: app_php-fpm
    volumes:
      - ./www:/var/www/html

