version: '3.8'

networks:
  my_custom_network:
    external: false  # Optional: Set to true if the network already exists
    driver: bridge  # Default driver for internal communication
    ipam:
      config:
        - subnet: 172.20.0.0/16  # Your desired subnet

services:
  app_nginx:
    image: nginx:latest
    container_name: app_nginx
    ports:
      - "172.20.0.3:8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx
      - ./www:/var/www/html
    depends_on:
      - app_php-fpm
    networks:
      my_custom_network:

  app_php-fpm:
    image: php:8.0-fpm
    container_name: app_php-fpm
    volumes:
      - ./www:/var/www/html
    networks:
      my_custom_network:

  f2b-docker:
    image: crazymax/fail2ban:latest
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - F2B_LOG_LEVE=DEBUG
      - F2B_DB_PURGE_AGE=30d
      - F2B_MAX_RETRY=5
      - F2B_ACTION=%(action_)s
      - F2B_IPTABLES_CHAIN=DOCKER-USER
      - TZ=America/Los_Angeles
    volumes:
      - /data/services/fail2ban/docker:/data
      - /etc/localtime:/etc/localtime:ro
      - /var/log:/var/log:ro
      - ./filter.d/nginx-badbots.conf:/etc/fail2ban/filter.d/nginx-badbots.conf
      - ./jail.d/nginx.conf:/etc/fail2ban/jail.d/nginx.conf
      - ./jail.d/nginx-http-auth.conf:/etc/fail2ban/jail.d/nginx-http-auth.conf
      - ./filter.d/nginx-nohome.conf:/etc/fail2ban/filter.d/nginx-nohome.conf
      - ./filter.d/nginx-noproxy.conf:/etc/fail2ban/filter.d/nginx-noproxy.conf
      - ./filter.d/nginx-noscript.conf:/etc/fail2ban/filter.d/nginx-noscript.conf
      - ./filter.d/nginx-forbidden.conf:/etc/fail2ban/filter.d/nginx-forbidden.conf
      - ./filter.d/nginx-no-file-directory.conf:/etc/fail2ban/filter.d/nginx-no-file-directory.conf
      - ./filter.d/nginx-errors.conf:/etc/fail2ban/filter.d/nginx-errors.conf
      #- ./jail.d/nginx-env.local:/etc/fail2ban/jail.d/nginx-env.local
      - ./filter.d/nginx-env.conf:/etc/fail2ban/filter.d/nginx-env.conf

# tes bintang 07

