name: Update Docker Compose and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          host='36.50.217.162'
          hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
          ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts

      # - name: Add SSH private key to SSH agent
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Change SSH_AUTH_SOCK permissions
      #   run: chmod 600 $SSH_AUTH_SOCK

      # repo = 'https://github.com/halilintar8/docker_nginx_php-fpm.git'
      # ssh ecustomer@36.50.217.162 "cd docker_nginx_php-fpm/ && git pull $repo"
      # ssh ecustomer@36.50.217.162 "cd docker_nginx_php-fpm/ && git pull https://github.com/halilintar8/docker_nginx_php-fpm.git"

      - name: SSH into server and update repository
        run: |
          git fetch --all
          git pull origin main --rebase                    
          
      - name: Docker-compose down
        run: sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ecustomer@36.50.217.162 "cd docker_nginx_php-fpm/ && docker-compose down"
        # run: docker-compose down

      - name: Docker-compose up
        run: sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ecustomer@36.50.217.162 "cd docker_nginx_php-fpm/ && docker-compose up -d"
        # run: docker-compose up -d

      - name: Check running containers
        run: sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ecustomer@36.50.217.162 "docker ps -a"
        # run: docker ps -a

      - name: Done
        run: echo "Deployment completed successfully"

# tes bintang 10
