name: Update Docker Compose and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key

      # - name: Add SSH private key to SSH agent
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Change SSH_AUTH_SOCK permissions
      #   run: chmod 600 $SSH_AUTH_SOCK

      - name: SSH into server and update repository
        run: |
          ssh ecustomer@36.50.217.162 "cd docker_nginx_php-fpm/ && git pull https://github.com/halilintar8/docker_nginx_php-fpm.git"

      - name: Docker-compose down
        run: sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ecustomer@36.50.217.162 "cd docker_nginx_php-fpm/ && docker-compose down"

      - name: Docker-compose up
        run: sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ecustomer@36.50.217.162 "cd docker_nginx_php-fpm/ && docker-compose up -d"

      - name: Check running containers
        run: sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ecustomer@36.50.217.162 "docker ps -a"

      - name: Done
        run: echo "Deployment completed successfully"

# tes bintang 02
